apiVersion: v1
kind: Service
metadata:
  name: observeai-ui
  namespace: observeai
spec:
  type: NodePort
  selector:
    app: observeai-ui
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30111
